image: Visual Studio 2017

environment:
  PYTHON: C:\Python36-x64

init:
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive

build_script:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - python --version
  - python build.py

artifacts:
  - path: build\*.zip
    name: Packaged
